version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: tarasmatiiv
          POSTGRES_DB: higo_db_test
          RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler -v 2.1.2
      - run: bundle install --with test
      - run: sudo apt install -y postgresql-client || true
      - run:
          name: Set up DB
          command: rake db:create RAILS_ENV=test
      - run:
          name: Run migrations
          command: rake db:migrate RAILS_ENV=test
      - run:
          name: Run seed
          command: rake db:seed RAILS_ENV=test
      - run:
          name: Run rspec
          command: |
          TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split
          bundle exec rspec ${TESTFILES}
