version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  bundle-install: circleci/bundle-install@2.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    environment:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler -v 2.1.2
      - ruby/bundle-install
