version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install mimemagic
          command: bundle update --conservative ffi
      - run:
          name: Install bundler
          command: gem install bundler -v 2.1.2

      - ruby/bundle-install
