development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  database: higo_db_development
  username: ivan
  password: ivan0407

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  database: higo_db_test
  username: ivan
  password: ivan0407

production:
  adapter: postgresql
  encoding: unicode
  username: higo_production
  database: higo_production_db
