development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3

test:
  adapter: postgresql
  encoding: unicode
  database: higo_test_db
  username: higo_test

production:
  adapter: postgresql
  encoding: unicode
  username: higo_production
  database: higo_production_db
